spring.application.name=feedback_management

server.port=8090

spring.datasource.url=jdbc:postgresql://db.qmjgecnkmchjixgamvnx.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=WLrvRDiAGbmu0jgI

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# spring.application.name=feedback_management
# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# server.port=8090
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format.sql=true

# jwt.secret=${JWT_SECRET}
# jwt.expiration=86400000

