# spring.application.name=feedback_management

# server.port=8081

# spring.datasource.url=jdbc:postgresql://db.qmjgecnkmchjixgamvnx.supabase.co:5432/postgres
# spring.datasource.username=postgres
# spring.datasource.password=WLrvRDiAGbmu0jgI
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format.sql=true

# jwt.secret=g6cB5bWjP1Z0iS2d5gFqv8Tn3M2JmQ4Q2qkM4z5lA8E=


spring.application.name=feedback_management
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

server.port=8090
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

