spring.application.name=feedback_management

server.port=8081

spring.datasource.url=${{ Postgres.DATABASE_URL }}
spring.datasource.username=cAOxMXmeJXCXpuasFdFDdTQfHTozqvLs
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true

jwt.secret=g6cB5bWjP1Z0iS2d5gFqv8Tn3M2JmQ4Q2qkM4z5lA8E=
